name: "CI Fork and Util tests"

on:
  schedule:
    - cron: "0 3 * * 1,3,5" # at 3:00 AM UTC on Monday, Wednesday and Friday

jobs:
  lint:
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-lint.yml@main"

  build:
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-build.yml@main"

  test-fork:
    needs: ["lint", "build"]
    secrets:
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-test.yml@main"
    with:
      foundry-fuzz-runs: 100
      foundry-profile: "test-optimized"
      fuzz-seed: true
      match-path: "test/fork/**/*.sol"
      name: "Fork tests"

  test-utils:
    needs: ["lint", "build"]
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-test.yml@main"
    with:
      foundry-profile: "test-optimized"
      match-path: "test/utils/**/*.sol"
      name: "Utils tests"

  notify-on-failure:
    if: failure() # Runs only if a failure occurs in any previous jobs
    runs-on: "ubuntu-latest"
    steps:
      - name: "Send Slack notification"
        uses: "rtCamp/action-slack-notify@v2"
        env:
          SLACK_CHANNEL: "#ci-notifications"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: "GitHub CI"
          SLACK_MESSAGE: "CI Workflow failed for ${{ github.repository }} on branch ${{ github.ref }} at job ${{ github.job }}."
